### ISSUE TITLE
None of the Condition inside word template working when template downloaded.

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport-docx#1]
Hi , i have a word template. On the server all the conditions inside the word ( i.e. `if` conditon ) woks completely fine . But when it comes to the HTML page , i've written the JS code 
```

function mysubmission() {
--
  jsreport.serverUrl = 'http://localhost:5488';
  var request = {
  template: {
  shortid: "rJqoGgosX"
  },
  data: data
  };
  jsreport.render(request);
  };
```
When the `Word template` downloads , none of the condition works . All the data comes as it is .
I've checked the `data` both are same as on JsReport server as well inside the HTML page.

**Comment by bjrmatos** [comment]
It seems we have missed this issue, sorry for that. I guess you no longer have the problem, right? if you still have this problem please open new issue with the template content and the data you are using for the render
