### ISSUE TITLE
Is is possible to nest a table within another table?

### ISSUE THREAD

**Issue by beardyfaceface** [jsreport/jsreport-docx#10]
Hi

Curious if it's possible to nest tables within other tables? I've been playing around with the docx recipe and any time I have nested tables the preview window fails to load the document and if I download the generated output Word gives an error message when trying to open the document.

**Comment by bjrmatos** [comment]
hi! you are right, looks like nested tables was not supported. i have pushed some changes to fix that, you can try it by installing the extensions from git `npm i jsreport/jsreport-docx`.

let us know how it goes, in case it fails you can provide us more details about the docx template you are using.
