### ISSUE TITLE
Ability to retain number formatting in Chart

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#14]
I created a chart template with the data formatted in local format for better readability. Example, instead of 100000 it appears 100,000. But the recipe does not retain this formatting. Any way we can achieve this by specifying any additional values in the template? Below is an example

[https://playground.jsreport.net/w/anon/BZzAg1N8](https://playground.jsreport.net/w/anon/BZzAg1N8)

**Comment by pofider** [comment]
Thank you for the demo. We will take a look at where's the problem.

**Comment by bjrmatos** [comment]
this should be fixed also on master, thanks for the example it really helped to reproduce the problem. will continue checking the other issues
