### ISSUE TITLE
Waterfall Chart in docx template does not work

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#15]
I tried to create a waterfall chart using the standard docx chart template. The chart does not load. There is no error but the chart is empty and the title text has a long text. Example is added below

[https://playground.jsreport.net/w/iamanoopmk/4PDfWcZU](https://playground.jsreport.net/w/iamanoopmk/4PDfWcZU)

Is there a different format that the data must be passed for waterfall chart?

**Comment by bjrmatos** [comment]
FYI as you can see the waterfall is not working because it uses an xml spec that is a bit different, we are working on implementing the support for that right now

**Comment by bjrmatos** [comment]
thanks, we were able to complete the support for this kind of chart, and also other charts

**Comment by iamanoopmk** [comment]
Any ETA on the new release?

**Comment by bjrmatos** [comment]
no clear time so far, we are still working on some improvements and then we will decide how to handle the next release, in the meantime please just install it from git.
