### ISSUE TITLE
Table row support

### ISSUE THREAD

**Issue by sebastian-schlecht** [jsreport/jsreport-docx#2]
Thanks for adding docx to jsreport!

Is there any forecast about adding helpers to insert rows in a table to this extension?

**Comment by pofider** [comment]
Would you please check out this example and elaborate on what you are missing?
Thank you

https://playground.jsreport.net/w/admin/q94T4AJa

**Comment by sebastian-schlecht** [comment]
hm..I must have missed that example. I've only seen one with column iteration. thanks!

**Comment by iamanoopmk** [comment]
@sebastian-schlecht 
Sorry to open this ticket again. I am trying to achieve the exact opposite to what you wanted, adding columns dynamically. I could not find an example with column iteration. Can you please add an example for column iteration on tables?
