### ISSUE TITLE
Support for scatterChart Type

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#20]
Currently when I include a chart with type scatter, I get the error saying "scatterChart" type is not supported. Will the support for these charts be added. Infact, we are trying a create a combo chart as shown in the below playground

[https://playground.jsreport.net/w/iamanoopmk/mecYBe_q](https://playground.jsreport.net/w/iamanoopmk/mecYBe_q)

Also, is there a way to programmatically add the axis min and max values to the chart?

**Comment by bjrmatos** [comment]
hi! did you try this on jsreport 2.10.0? this is the output when using 2.10.0 which looks correct. the playground is still using jsreport 2.8.0 so the only way to test this is using 2.10.0 on your local server.

<img width="1178" alt="Captura de pantalla 2020-10-12 a la(s) 11 41 44 a  m" src="https://user-images.githubusercontent.com/4262050/95771328-74cef700-0c80-11eb-941d-f7a21391996a.png">


> Also, is there a way to programmatically add the axis min and max values to the chart?

it was not supported, however, i've added support for it just now, at least for the scatter chart (until we can verify the same implementation can work across all other chart types), this is fairly new so all chart options are not supported, i've just started with the axis min, max, if the axis should be visible or not, and also the step size of the axis.

you can pass these options as part of the docxChart call, `{{docxChart data=chart_data options=chart_options}}`

an example of the options looks like these:

```js
{
    "chart_data": {
        "labels": ["6", "6.5", "7"],
        "datasets": [
            {
                "label": "Series 1",
                "data": [4, 5, 6]
            },
            {
                "label": "Series 2",
                "data": [2, 7, 1]
            },
            {
                "label": "Series 3",
                "data": [7, 6, 8]
            }
        ]
    },
    "chart_options": {
        "scales": {
            "xAxes": [{
                "display": true,
                "ticks": {
                    "stepSize": 0.2,
                    "min": 6,
                    "max": 7
                }
            }],
            "yAxes": [{
                "display": true,
                "ticks": {
                    "stepSize": 1,
                    "min": 1,
                    "max": 13
                }
            }]
        }
    }
}
```

to test this you need to install from git `npm i jsreport/jsreport-docx`

let me know if these changes works ok for you.

**Comment by bjrmatos** [comment]
hmm you say that this is also a combo-chart, right? i was thinking that all combo-charts only support two data series, but i see this docx contains three data series, just that the second data serie is not shown because of the coincidence that its values are overlapped by values of other data serie. may I ask you the steps you done to create this chart?

**Comment by iamanoopmk** [comment]
Thank you for the response. I will try the updated version and let you know what I find.

About the combo chart, I am not sure if that is a limitation. By default, I was given an option to add 3 series when I selected the combo chart. I used MS Office 2016 if that helps

**Comment by iamanoopmk** [comment]
I upgraded both jsreport and docx packages. I was able to plot the combo chart. however, the chart options did not seem to work. I tried the example that you uploaded but the options were not applied. Not sure if that is part of the latest update

**Comment by bjrmatos** [comment]
I've pushed more changes, including the support for the combo charts, not sure why it does not work for you. can you try reinstalling from git again?

here is the example I'm using

[export-combo-scatter-chart.zip](https://github.com/jsreport/jsreport-docx/files/5381128/export-combo-scatter-chart.zip)

and here is the result (note how the y axis min, max, step values have changed)

<img width="1067" alt="result" src="https://user-images.githubusercontent.com/4262050/96051465-2e74c600-0e41-11eb-9113-9ba14549377b.png">

**Comment by iamanoopmk** [comment]
Thank you for the quick response. I updated again with the new changes and now it is working. I am able to set the axis options using the method described by you.
