### ISSUE TITLE
Chart with Secondary Axis does not plot correctly

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#21]
I am trying a create a chart with primary y-axis as column and secondary y-axis as line. I use the combo-chart option in MS Word. Below playground has the example.

The secondary y-Axis is set to column instead of line and the data is also set wrong. The scale seems to be off.

Not sure if this will be fixed if the issue #20 is fixed.

[https://playground.jsreport.net/w/anon/vfJw5WRZ](https://playground.jsreport.net/w/anon/vfJw5WRZ)

**Comment by bjrmatos** [comment]
combo-charts are based on two charts internally, I will need to do a bit of digging to support this, will let you know when it is ready

**Comment by bjrmatos** [comment]
I've added the support for the combo chart, give it a try and let me know if you find an issue.

**Comment by iamanoopmk** [comment]
I will test this and get back to you

**Comment by iamanoopmk** [comment]
This is working as expected. I tried separate axes for a column and line chart and it is plotting as expected. Thank you for the quick fix.
