### ISSUE TITLE
Adding custom labels to Scatter plot

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#22]
Creating this issue as I did not find any doc on this subject.

Requirement is that we want to display custom labels on the chart bubble. In Word we achieve this enabling datalabels and then specifying a column that contains the labels. Is there a way to add this here. I tried a couple of obvious things like adding one more list named datalables and passing the datalables list in the chart options. But did not work. I have attached a template as an example. 

[scatter_labels.zip](https://github.com/jsreport/jsreport-docx/files/5399414/scatter_labels.zip)

**Comment by bjrmatos** [comment]
hi! yes, data labels are currently not supported, i will add this to our backlog, and update the issue when it is ready

**Comment by iamanoopmk** [comment]
Hello, Do you have a rough estimation on the ETA. I can plan accordingly. Thank you.

**Comment by bjrmatos** [comment]
we will try to look at it during the next week, but can't promise anything about an exact date when its done

**Comment by bjrmatos** [comment]
we have added support for data labels, starting with just `scatterChart` until we can verify that other chart types work the same way.

<img width="1124" alt="Captura de pantalla 2020-11-02 a la(s) 6 09 26 p  m" src="https://user-images.githubusercontent.com/4262050/97929194-9dee1f00-1d36-11eb-9b86-3da2badd3828.png">


the expected data to configure the data labels looks like this.

```js
{
    "chart_data": {
        "labels": [0.7, 1.8, 2.6],
        "datasets": [{
            "label": "Series 1",
            "data": [2.7, 3.2, 0.8],
            "dataLabels": ["A1", {
                "value": "B1",
                "position": "left"
            }, "C1"]
        }]
    }
}
```

`dataLabels` must an array of either an string or object with "value", alternative to configure the position of the data labels you can pass "position", allowed values are: `left`, `right`, `center`, `top`, `bottom`

do an install from git `npm i jsreport/jsreport-docx` and let me know how this works for you.
