### ISSUE TITLE
Image from URL

### ISSUE THREAD

**Issue by sebastian-schlecht** [jsreport/jsreport-docx#3]
Hey,

another query - is it supported, or planned, to add support for images from URL instead of data URIs?

For our use-case, we have a bunch of entities which themselves contain images (URLs). I need to iterate over these entities (e.g. create one page for each) and then iterate through the attached images. I think with the current approach (image from placeholder),  this is not possible, correct?

**Comment by pofider** [comment]
We may consider it in the future.
Right now there is an easy solution you can apply.

You can download your images and convert them to dataURI upfront using jsreport custom script and beforeRender hook
https://jsreport.net/learn/scripts

**Comment by sebastian-schlecht** [comment]
For some reason I got a crash when trying this. Is this known? Otherwise I’d provide a detailled error report.

**Comment by pofider** [comment]
Please share more details.

**Comment by sebastian-schlecht** [comment]
> You can download your images and convert them to dataURI upfront using jsreport custom script and beforeRender hook
https://jsreport.net/learn/scripts

I just revisited this & I re-thought the approach and discovered that this would probably be suboptimal for us - we do have a bunch of templates that we want to render, yet the context we send is quite static, i.e. contains urls to images. Yet, not all the reports we want to render to actually use links, hence we wouldn't need to download them in the first place, introducing quite some unnecessary overhead. I think best would be to add the download part to the actual docxImage helper, such that only what really is required will be downloaded. I would be willing to contribute as well in case you can give me some pointers where to start.

**Comment by pofider** [comment]
Fixed in #5 
Thank you for the contribution @sebastian-schlecht 

We will this week update npm dep and release it along with the jsreport 2.7.0.
