### ISSUE TITLE
Special characters not escaped

### ISSUE THREAD

**Issue by jper92** [jsreport/jsreport-docx#31]
Hi, 

I have a project where our customers enter a text that then is passed to jsreport to generate a docx, the issue is that the payload we're passing seems like this:

```
{ "title": "A random text with a special character \u0000" }
```

And in the template we have something like this:
```
{{ title }}
```

The issue is that the generated docx is invalid, apparently the special characters won't be escaped and the office suites will fail to load:
https://playground.jsreport.net/w/anon/NjdMzfBD

Should the library escape those characters so that the generation doesn't fail?

**Comment by pofider** [comment]
Thank you for this topic.
We will take a deeper look and decide if the escape should be automatic or we should at least document how to do it.

**Comment by bjrmatos** [comment]
this should be fixed on master
