### ISSUE TITLE
Axis values not being set when looping charts

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#34]
We are trying to create a few charts whose data is in a list. Each row in the list has the datset, labels, title and axis labels.

The chart and title are rendered correctly but the axis labels are not displayes. Below is a playground showing the issue with two charts in a loop.

[https://playground.jsreport.net/w/iamanoopmk/Mu2bkQ7J](https://playground.jsreport.net/w/iamanoopmk/Mu2bkQ7J)

**Comment by bjrmatos** [comment]
i have fixed the problem with the secondary axis, it is now available in master
