### ISSUE TITLE
Limited parallelism for downloading remote images

### ISSUE THREAD

**Issue by sebastian-schlecht** [jsreport/jsreport-docx#9]
Hey,

we are looking at a use-case where we might add hundreds of images to a single rendered document. IMO in this case it makes sense to limit the amount of parallel downloads per job to a certain, fixed amount to avoid blocking the whole node's I/O. 

https://github.com/jsreport/jsreport-docx/blob/master/lib/postprocess/image.js#L124

I can pull up a PR if you guys think this is worth adding.

**Comment by bjrmatos** [comment]
thanks, we think this makes sense, we have added new option `extensions.docx.imageFetchParallelLimit` which defaults to 5 to control this operation. for now you can try it by installing the extension from git `npm i jsreport/jsreport-docx` until we release a new version of it. if you have more feedback about that let us know

**Comment by sebastian-schlecht** [comment]
Thanks @bjrmatos !
